# ServiceAccount for book-service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-service-account
  namespace: default

---
# Role - permissions limits
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: book-service-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding - links the ServiceAccount to Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: book-service-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: book-service-account
    namespace: default
roleRef:
  kind: Role
  name: book-service-role
  apiGroup: rbac.authorization.k8s.io