spring.application.name=book-service
server.port=8081

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/bookdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


